SET IDENTITY_INSERT [dbo].[Product] ON
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (3, N'Nike React Infinity Run Flyknit 3', N'Nike là một trong những thương hiệu thể thao nổi tiếng nhất trên thế giới được thành lập tại Mỹ. Nike là nhà cung cấp giày thể thao lớn nhất trên thế giới và cũng là một nhà sản xuất thiết bị thể thao danh tiếng. Những đôi giày thể thao của Nike rất được ưu chuộng trên toàn thế giới thông qua các con số doanh thu khổng lồ mà Nike nhận được.Khách hàng từ mọi lứu tuổi , từ mọi từng lớp đều rất yêu thích những đôi giày mà Nike mang tới cho các tín đồ yêu thích giày trên toàn thế giới. Chúng ta có thể bắt gặp rất nhiều siêu sao, người mẫu, ca sĩ mang trên chân những đôi giày vô cùng đẹp và độc đáo đến từ thương hiệu này và điều đó làm cho Nike càng thêm trendy.Ưu điểm của những đôi giày Nike mang lại vô cùng thoải mái và vô cùng đa dạng màu sắc cũng nhiêu kiểu dáng , mang đến nhiều sự lựa chọn cho mọi người.
', 3, CAST(3600000.00 AS Decimal(18, 2)), N'~/Content/images/nike_RIRFlyknit3.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (4, N'Nike React Miler 3', N'Nike là một trong những thương hiệu thể thao nổi tiếng nhất trên thế giới được thành lập tại Mỹ. Nike là nhà cung cấp giày thể thao lớn nhất trên thế giới và cũng là một nhà sản xuất thiết bị thể thao danh tiếng. Những đôi giày thể thao của Nike rất được ưu chuộng trên toàn thế giới thông qua các con số doanh thu khổng lồ mà Nike nhận được.Khách hàng từ mọi lứu tuổi , từ mọi từng lớp đều rất yêu thích những đôi giày mà Nike mang tới cho các tín đồ yêu thích giày trên toàn thế giới. Chúng ta có thể bắt gặp rất nhiều siêu sao, người mẫu, ca sĩ mang trên chân những đôi giày vô cùng đẹp và độc đáo đến từ thương hiệu này và điều đó làm cho Nike càng thêm trendy.Ưu điểm của những đôi giày Nike mang lại vô cùng thoải mái và vô cùng đa dạng màu sắc cũng nhiêu kiểu dáng , mang đến nhiều sự lựa chọn cho mọi người.
', 3, CAST(3500000.00 AS Decimal(18, 2)), N'~/Content/images/nike_RMiler3.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (5, N'Nike Metcon 7', N'Nike là một trong những thương hiệu thể thao nổi tiếng nhất trên thế giới được thành lập tại Mỹ. Nike là nhà cung cấp giày thể thao lớn nhất trên thế giới và cũng là một nhà sản xuất thiết bị thể thao danh tiếng. Những đôi giày thể thao của Nike rất được ưu chuộng trên toàn thế giới thông qua các con số doanh thu khổng lồ mà Nike nhận được.Khách hàng từ mọi lứu tuổi , từ mọi từng lớp đều rất yêu thích những đôi giày mà Nike mang tới cho các tín đồ yêu thích giày trên toàn thế giới. Chúng ta có thể bắt gặp rất nhiều siêu sao, người mẫu, ca sĩ mang trên chân những đôi giày vô cùng đẹp và độc đáo đến từ thương hiệu này và điều đó làm cho Nike càng thêm trendy.Ưu điểm của những đôi giày Nike mang lại vô cùng thoải mái và vô cùng đa dạng màu sắc cũng nhiêu kiểu dáng , mang đến nhiều sự lựa chọn cho mọi người.
', 3, CAST(3829000.00 AS Decimal(18, 2)), N'~/Content/images/nike_Metcon7.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (6, N'Nike SB Zoom Blazer Mid EK', N'Nike là một trong những thương hiệu thể thao nổi tiếng nhất trên thế giới được thành lập tại Mỹ. Nike là nhà cung cấp giày thể thao lớn nhất trên thế giới và cũng là một nhà sản xuất thiết bị thể thao danh tiếng. Những đôi giày thể thao của Nike rất được ưu chuộng trên toàn thế giới thông qua các con số doanh thu khổng lồ mà Nike nhận được.Khách hàng từ mọi lứu tuổi , từ mọi từng lớp đều rất yêu thích những đôi giày mà Nike mang tới cho các tín đồ yêu thích giày trên toàn thế giới. Chúng ta có thể bắt gặp rất nhiều siêu sao, người mẫu, ca sĩ mang trên chân những đôi giày vô cùng đẹp và độc đáo đến từ thương hiệu này và điều đó làm cho Nike càng thêm trendy.Ưu điểm của những đôi giày Nike mang lại vô cùng thoải mái và vô cùng đa dạng màu sắc cũng nhiêu kiểu dáng , mang đến nhiều sự lựa chọn cho mọi người.
', 3, CAST(2649000.00 AS Decimal(18, 2)), N'~/Content/images/nike_SBZBMidEK.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (7, N'Adidas Stan Smith ', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(2500000.00 AS Decimal(18, 2)), N'~/Content/images/stanSmith.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (8, N'Adidas Yeezy 350 V2 Beluga', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(6000000.00 AS Decimal(18, 2)), N'~/Content/images/y350V2_B.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (9, N'Adidas Harden Stepback 3 ', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(23000000.00 AS Decimal(18, 2)), N'~/Content/images/hardenS3.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (10, N'Adidas Dame 8', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(3200000.00 AS Decimal(18, 2)), N'~/Content/images/dame8.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (11, N'Adidas Harden Vol 6', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(4000000.00 AS Decimal(18, 2)), N'~/Content/images/hardenV6.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (12, N'Adidas Duramo 10', N'Adidas là một công ty đa quốc gia đến từ Đức, chuyên sản xuất giày dép, quần áo và phụ kiện. Adidas, thành công ty lớn thứ hai thế giới chuyên sản xuất các sản phẩm thời trang thể thao và thời trang. Sản phẩm của hãng hiện đang có mặt trên hầu khắp các thế giới.
Các sản phẩm chính của thương hiệu Adidas bao gồm dép, quần áo, mũ, tất, túi xách thể thao… Đặc biệt là những đôi giày mang thương hiệu trứ danh. Ưu điểm của các sản phẩm thương hiệu Adidas là luôn được làm từ những chất liệu tốt nhất và được thiết kế với kiểu dáng tỉ mỉ, kín đáo và tinh tế. Từng đường may đều mang đến cho người sử dụng cảm giác thoải mái, dễ chịu.
', 1, CAST(1300000.00 AS Decimal(18, 2)), N'~/Content/images/duramo10.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (13, N'Vans Authentic Classic ', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(1450000.00 AS Decimal(18, 2)), N'~/Content/images/vans1.png', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (14, N'Vans Vault OG Classic Slip On', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(2600000.00 AS Decimal(18, 2)), N'~/Content/images/vans3.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (15, N'Vans Canvas Old Skool Classic True White', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(1750000.00 AS Decimal(18, 2)), N'~/Content/images/vans5.png', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (16, N'Vans Classic SK8-HI', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/vans6.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (17, N'Vans Ouroboros Slip-On', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/vans7.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (18, N'Vans Ouroboros SK8-HI', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(2100000.00 AS Decimal(18, 2)), N'~/Content/images/vans8.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (19, N'Vans x National Geographic SK8-HI Reissue 138', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(3100000.00 AS Decimal(18, 2)), N'~/Content/images/vans9.png', -56)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (20, N'Vans X Moca Judy Baca Authentic', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
', 5, CAST(2850000.00 AS Decimal(18, 2)), N'~/Content/images/vans10.png', 98)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (21, N'Converse Chuck Taylor All Star 70 Plus', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(2500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse1.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (22, N'Converse Chuck Taylor All Star Dainty', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse2.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (23, N'Converse Chuck Taylor All Star Lift Platform Canvas', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1800000.00 AS Decimal(18, 2)), N'~/Content/images/Converse3.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (24, N'Converse Chuck Taylor All Star 1970s Archive Paint Splatter', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(2500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse4.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (25, N'Converse Chuck Taylor All Star 1970s My Story', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(2000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse5.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (26, N'Converse Chuck Taylor All Star Double Stack Lift My Story', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1800000.00 AS Decimal(18, 2)), N'~/Content/images/Converse6.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (27, N'Converse Chuck Taylor All Star Wordmark', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse7.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (28, N'Converse Chuck Taylor All Star Gamer Low-Top', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse8.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (29, N'Converse Chuck Taylor All Star Valentine''s Day', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse9.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (30, N'Converse Chuck Taylor All Star 1970s Mi Gente', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(2000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse10.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (31, N'Converse Chuck Taylor All Star Create Future', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse12.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (32, N'Converse Chuck Taylor All Star Twisted Classic Logo Play', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse11.jpg', 100)
SET IDENTITY_INSERT [dbo].[Product] OFF
