//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerStore.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customer()
        {
            this.OrderProes = new HashSet<OrderPro>();
        }
        [Display(Name = "Mã Cus")]
        public int IDCus { get; set; }
        [Required(ErrorMessage = "Tên bị trống ...")]
        [Display(Name = "Tên Cus")]
        public string NameCus { get; set; }
        [Required(ErrorMessage = "SĐT bị trống ...")]
        [Display(Name = "Số điện thoại")]
        public string PhoneCus { get; set; }
        public string EmailCus { get; set; }
        [Required(ErrorMessage = "Tên đăng nhập bị trống ...")]
        [Display(Name = "Tên Cus")]
        public string UserName { get; set; }
        [DisplayName("Nhập mật khẩu")]
        [Required(ErrorMessage = "Mật khẩu bị trống ...")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        [NotMapped]
        [Compare("Password")]
        [DisplayName("Nhập lại mật khẩu")]
        public string ConfirmPass { get; set; }
        [NotMapped]
        public string ErrorLogin { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderPro> OrderProes { get; set; }
    }
}
