//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SneakerStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Voucher
    {
        public string IDVoucher { get; set; }
        public string MaVoucher { get; set; }
        public Nullable<int> PhanTramDis { get; set; }
        public string MotaVoucher { get; set; }
    }
}
